Bug fixs | clean up | expansion

diff --git a/p_tool b/p_tool
--- a/p_tool
+++ b/p_tool
@@ -15,7 +15,7 @@ echo -e "$(tput setaf 4)# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## 
 
 #Create directory for use by ptool
 function exist_mkdir () {
-ls /etc/ptool
+sudo ls /etc/ptool
 }
 echo
 echo
@@ -44,17 +44,18 @@ echo
 echo "Exit:  [x]"
 echo 
 echo "Please select a letter corresponding to your selection:   "
-echo "$(tput setaf 3)[s]$(tput sgr 0) : Initial Server Set Up. Very Basic.  "
-echo "$(tput setaf 3)[p]$(tput sgr 0) : Partition or Fallocate Drives & Create RAID.  "
-echo "$(tput setaf 3)[a]$(tput sgr 0) : Add New User. Manage Permissions & Umask.  "
-echo "$(tput setaf 3)[u]$(tput sgr 0) : Update Server.  "
-echo "$(tput setaf 3)[m]$(tput sgr 0) : Create & Configure Swap, Swappiness & Kernel Message.  "
-echo "$(tput setaf 3)[x]$(tput sgr 0) : Exit This Script.  "
+echo 
+echo "$(tput setaf 3)[s] : Initial Server Set Up. Very Basic.$(tput sgr 0)  "
+echo "$(tput setaf 3)[p] : Partition or Fallocate Drives & Create RAID.$(tput sgr 0)  "
+echo "$(tput setaf 3)[a] : Add New User. Manage Permissions & Umask.$(tput sgr 0)  "
+echo "$(tput setaf 3)[u] : Update Server.$(tput sgr 0)  "
+echo "$(tput setaf 3)[m] : Create & Configure Swap, Swappiness & Kernel Message.$(tput sgr 0)  "
+echo "$(tput setaf 3)[x] : Exit This Script.$(tput sgr 0)  "
 echo
-read action
+read -p "Enter Selection:   " action
 
 #Menu Options
-while true ; do
+while [[ true != false ]] ; do
 	case $action in	
 		u) echo "Server Updating. Please Wait...";;
 		p) echo "Initizializing Partitioning and RAID Script. Please Wait...";;
@@ -66,95 +67,147 @@ while true ; do
 
 #System Update
 	if [[ $action == u ]] ; then
-		sudo dnf -y update || apt -y update
+		
+		echo "Which Distribution Is In use?   "
+		echo
+		echo "$(tput setaf 2)[1] : CentOS | RedHat | Fedora Distributions.$(tput sgr 0)  "
+		echo "$(tput setaf 2)[2] : Debian | Ubuntu Distributions.$(tput sgr 0)  "
+		echo 
+		read -p "Enter Number:   "  i
+		case $i in
+			1) echo "CentOS/RedHat/Fedora";;
+			2) echo "Debian/Ubuntu";;
+		esac
+		if [[ $i -eq 1 ]] ; then
+			sudo dnf -y update
+		elif [[ $i -eq 2 ]] ; then
+			sudo apt -y update
+		fi
+		break
 
 #Pull Partition scipt and run		
 	elif [[ $action == p ]] ; then
-		cd /etc/ptools
-		wget https://port443.uk/ptools
-		sudo chmod 700 ptools
-		sudo bash ptools
+		cd /etc/ptool
+		function sh () {
+		cat /etc/ptool/ptool-part
+		}
+		if sh ; then
+			sudo bash ptool-part
+		else
+			sudo wget https://raw.githubusercontent.com/Junior-ptool/p_tool-practical-tool/master/ptool-part
+                        sudo chmod 700 /etc/ptool/ptool-part
+			sudo bash ptool-part
+		fi
+		
 
 #Set Up Servers		
 	elif [[ $action == s ]] ; then
 		echo "Would you like to generate a ssh keypair and scan your additional nodes to collect their keys?  "
 		read -p "[Y] or [N]:  " quest
 		if [[ $quest == Y ]] || [[ $quest == y ]] ; then
-			echo "What is the host IP?  "
+			echo "Enter The Hostname Or IP.  "
 			read host
-			sudo mkdir ~/.ssh
-			sudo mkdir ~/.ssh/known_hosts
-			sudo chmod 600 ~/.ssh/known_hosts
+			function ssh () {
+			ls ~/.ssh
+			}
+			if ssh ; then
+				echo ""
+			else
+				sudo mkdir ~/.ssh
+				sudo mkdir ~/.ssh/known_hosts
+				sudo chmod 600 ~/.ssh/known_hosts
+			fi
+
 #Copy keys from host
 			sudo ssh-keyscan $host ~/.ssh/known_hosts
 			sudo ssh-keygen -t rsa 
 			sudo ssh-copy-id $host
 			
+			
 		fi
 
 #SSH Hardening
 		echo "Would you like to reduce Brute Force Noise and change your SSH Port?  "
-		read -p "[Y] or [No]:  " p_num
-
-		if [[ $p_num == Y ]] || [[ $p_num == y ]] ; then
+		echo 
+		read -p "[Y] or [N]:   " ssh_port
+		if [[ $ssh_port == Y ]] || [[ $ssh_port == y ]] ; then
+			echo 
+			echo "What Port Do You Want SSH To Respond To?   "
+			echo
+			read -p "Port Number:  " p_num
+			echo
 			echo Port $p_num >> /etc/ssh/sshd_config
-			if [[ $? -eq 0 ]]; then
+			if [[ $? -eq 0 ]] ; then
 				sudo systemctl restart sshd
 				echo "SSH Port now updated. Please open a new shell and test it before closing this one."
 			else
 				echo "There has been an permission issue hardening your SSH. Are you root or a sudoer?  "
 			fi
-
-#Setting Hostname And Timezone
-		echo 
-		echo "What is the hostname for the server? "
-		read hostname
-		hostnamectl set-hostname $hostname
-		echo 
-		echo "What is your time zone? e.g Europe/London"
-		read time
-		timedatectl set-time $time
+				
+			echo 
+			echo "What is the hostname for the server? "
+			read -p "Pick Hostname:   " hostname
+			sudo hostnamectl set-hostname $hostname
+			echo 
+			echo "What is your time zone? e.g Europe/London"
+			read -p "Correct Syntax Needed:   " time
+			sudo timedatectl set-timezone $time
+			
+		else
+			echo "SSH Hardening And Basic Set Up has not taken place.  "
 		fi
 		break
 
+function flag () {
+swapon -s
+}
+declare -xf flag
 #Optimise Server with swappiness and overcommit
 	elif [[ $action == m ]] ; then
 		echo 
 		echo "What swappiness would you like to apply \(Max 100\)?  "
-		read swap_level
-		sysctl vm.swappiness=$swap_level
+		read -p "Enter Figure:   " swap_level
+		sudo sysctl vm.swappiness=$swap_level
 		echo 
 		echo "Would you like to overcommit memory?  "
-		read -p "[Y] or [N]" oc
+		read -p "[Y] or [N]:  " oc
 
 		if [[ $oc == Y ]] || [[ $oc == y ]] ; then
 			echo 1 > /proc/sys/vm/overcommit_memory
 		fi
 
 		echo "What would you like to set msgmax to? \(Max: 131072\) "
-		read
-		echo $REPLY > /proc/sys/kernel/msgmax
+		read -p "Enter Figure:   "
+		sudo echo $REPLY > /proc/sys/kernel/msgmax
 		echo
 		echo "Would you like to create swap?  "
-		read -p "[Y] [N]" fal_swap
+		read -p "[Y] [N]:  " fal_swap
+		function flag2 () {
+		swapon $swap
+		}
+		declare -xf flag2
 
 #Create swap if wanted.
 		if [[ $fal_swap == Y ]] || [[ $fal_swap == y ]] ; then
 			echo
 			echo "What size would you like your swap to be in MB or GB?  "
 			echo
-			read swap_size
+			read -p "Enter Figure:  " swap_size
 			echo
 			echo "Creating swap"
 			echo
-			swap.disk=/etc/ptools/swap.disk
-			fallocate -l $swap_size $swap.disk
-			mkswap $swap.disk
-			swapon $swap.disk
-			swapon -s
+			swap=/etc/ptool/swap.disk
+			sudo fallocate -l $swap_size $swap
+			sudo chmod 600 $swap
+			sudo mkswap $swap
+			su -c flag2 
+			su -c flag 
 			echo
+			free -h
 			echo "Swap Successfully Created.  "
 			echo
+			echo "$swap	none	ext4	swap	defaults	0	0" >> /etc/fstab
+			
 		else
 			echo
 			echo "No Swap Will Be Added"
@@ -163,42 +216,43 @@ while true ; do
 
 		break
 
-#Add User ANd Password
+#Add User And Password
 	elif [[ $action == a ]] ; then
-		add=$(egrep "^$user" /etc/passwd)
-
-		while [[ $add -eq 1 ]] ; do
+		function add () {
+		sudo grep -e "^$user" /etc/passwd
+		}
+		while true ; do
 			echo
 			echo "What is the name of the user you would like to add?  "
 			echo
-			read user
-			grep -e "^$user" /etc/passwd > /dev/null
+			read -p "Username:   "user
+			"add" > /dev/null
 
 			#Check if user exist
-			if [[ $? -eq 0 ]]; then
+			if add ; then
 				echo "Username $user Already Exists! Please try again.  "
-			fi
+			else
 
+				echo
+				echo "Please enter the new users password.  "
+				echo
+				read -s -p "Enter Password:   " password
+				pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+				sudo useradd -m -p "$pass" "$user"
+
+				if [[ $? -eq 0 ]] ; then
+					echo "User $user Has Been Successfully Added.  "
+					break
+				else
+					echo "Failed To Add User.  "
+				fi
+			fi
 		done
 
-
-		echo
-		echo "Please enter the new users password.  "
-		echo
-		read -s -p "Enter Password:   " password
-		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
-		useradd -m -p "$pass" "$user"
-
-		if [[ $? -eq 0 ]] ; then
-			echo "User $user Has Been Successfully Added.  "
-		else
-			echo "Failed To Add User.  "
-		fi
-
 #Exit Script
-	else
-		if [[ $action == x ]] ; then
-			exit 0
-		fi
+	elif [[ $action == x ]] ; then
+		break
+		exit 1
+		
 	fi
 done 
